---
name: IO-Vec
version: 0.02
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: writev and readv in perl
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.006
build_requires:
  Test::More: 0
provides:
  IO::Vec:
    file: lib/IO/Vec.pm
    version: 0.02
  IO::Vec::Constants:
    file: lib/IO/Vec.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
